# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/miuicamera-sky/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),miuicamera-sky)

endif
